# recent topics page (full header)
avathar_recenttopics_page:
    path: /rt
    defaults: { _controller: avathar.recenttopics.controller.page_controller:display}

# recent topics simple page (no header, for iframe embedding)
avathar_recenttopics_simple:
    path: /rt/simple
    defaults: { _controller: avathar.recenttopics.controller.page_controller:display_simple}
