services:
    avathar.recenttopicsav.controller.page_controller:
        class: avathar\recenttopicsav\controller\page_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@avathar.recenttopicsav.functions'
            - '@user'

    avathar.recenttopicsav.functions:
        class: avathar\recenttopicsav\core\recenttopics
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@language'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@config_text'
            - '@?phpbb.collapsiblecategories.operator'
            - '@?avathar.postlove.topic_likes'
    avathar.recenttopicsav.listener:
        class: avathar\recenttopicsav\event\listener
        arguments:
            - '@avathar.recenttopicsav.functions'
            - '@config'
            - '@request'
            - '@controller.helper'
            - '@language'
        tags:
            - { name: event.listener }
    avathar.recenttopicsav.ucp_listener:
        class: avathar\recenttopicsav\event\ucp_listener
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
